name: PR checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  vsix-validate:
    name: VSIX package validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: CI setup
        uses: ./.github/actions/ci-setup

      - name: Validate VSIX build
        run: pnpm exec vsce package
